#!/usr/bin/php
<?php
include_once 'yaqds-init.php';
include_once 'local/main.class.php';

$main = new Main([
    'debugLevel'     => 9,
    'debugType'      => DEBUG_COMMENT,
    'debugBuffer'    => false,
    'debugLogDir'    => APP_LOGDIR,
    'errorReporting' => false, 
    'sessionStart'   => false,
    'memoryLimit'    => null,
    'sendHeaders'    => true,
    'database'       => true,
    'dbConfigDir'    => APP_CONFIGDIR,
    'fileDefine'     => APP_CONFIGDIR.'/settings.json',
    'dbDefine'       => null,
    'input'          => true,
    'html'           => false,
    'adminlte'       => false,
]);

$apiOptions = ['baseUrl' => MY_API_URL, 'authToken' => MY_API_AUTH_TOKEN];

if (!$main->buildClass('api','MyAPI',$apiOptions,'local/myapi.class.php')) { exit; }

$result = $main->obj('api')->v1MapList();

var_dump($result,$main->obj('api')->clientError());

?>
