#!/bin/bash

### Enable shell debugging
#set -x

pushd . &> /dev/null

SCRIPTDIR=${BASH_SOURCE%/*}
BASEDIR=$(dirname -- $(realpath $SCRIPTDIR))
JQBIN=$(which jq 2> /dev/null)

if [ -z "$JQBIN" ]; then
    JQBIN="${HOME}/jq"
fi

if [ ! -f "$JQBIN" ]; then
    print "Cannot find jq binary, halting...\n"
    exit;
fi

DEPLOYDIR="$BASEDIR/deploy"
DBDUMPDIR="$BASEDIR/quarm/db"
VERSIONJSON="$BASEDIR/etc/version.json"
SETTINGSJSON="$BASEDIR/etc/settings.json"
DBCONFIGFILE="$BASEDIR/etc/db.conf"
SCRIPTSDIR="$BASEDIR/scripts"

### Database connect string parameters
DBHOST=$(cat $DBCONFIGFILE | base64 -d | $JQBIN -r '.hostname')
DBUSER=$(cat $DBCONFIGFILE | base64 -d | $JQBIN -r '.username')
DBNAME=$(cat $DBCONFIGFILE | base64 -d | $JQBIN -r '.database')
DBPASS=$(cat $DBCONFIGFILE | base64 -d | $JQBIN -r '.password')

### Remote latest available downoad, filename, and date
PHPINCLUDEDIR=$(cat $SETTINGSJSON | $JQBIN -r '.PHP_INCLUDE_DIR')
LATESTAVAIL=$(wget -q -O - --header "Accept: application/vnd.github.v3+json" https://api.github.com/repos/SecretsOTheP/EQMacEmu/contents/utils/sql/database_full | $JQBIN -r '.[length -1].download_url')
AVAILFILE=$(basename $LATESTAVAIL)
AVAILDATE=$(echo "$AVAILFILE" | grep -Eo '[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}' | tr -d '-')
QUARMDBVER=$(echo "$AVAILFILE" | sed -E 's/.*?([[:digit:]]{4})-([[:digit:]]{2})-([[:digit:]]{2})-([[:digit:]]{2})_([[:digit:]]{2}).*/\1\2\3-\4\5/')

### Local install date
LATESTINSTALL=$(cat $DBDUMPDIR/latest 2> /dev/null)

### If we're up to date, there's nothing to do
if [ "$AVAILDATE" == "$LATESTINSTALL" ] && [ -d "$DBDUMPDIR/$LATESTINSTALL" ]; then
    printf "\nWe are running the latest database. ($AVAILDATE)\n\n"
    exit
fi

### Start synchronizing new database

printf "* Making new quarm database directory $AVAILDATE\n"
mkdir -p $DBDUMPDIR/$AVAILDATE
cd $DBDUMPDIR/$AVAILDATE

printf "* Getting latest dump file from repo $AVAILFILE\n"
wget -q $LATESTAVAIL

printf "* Extracting latest dump file\n"
tar zxf $AVAILFILE
rm $AVAILFILE

### Remove MariaDB bugged sandbox line
printf "* Preparing quarm data file\n"
cat quarm_*.sql | sed '/^\/\*/d' > quarm-import.sql

export MYSQL_PWD="$DBPASS"

printf "* Purging existing tables\n"
mysql -h $DBHOST -u $DBUSER $DBNAME < drop_system.sql

printf "* Importing new tables\n"
mysql -h $DBHOST -u $DBUSER $DBNAME < quarm-import.sql

printf "* Executing custom table queries\n"
mysql -h $DBHOST -u $DBUSER $DBNAME < $DEPLOYDIR/sql/yaqds-tables.sql

printf "* Executing scripted spawn insertion\n"
INCLUDEPATH=$([ "$PHPINCLUDEDIR" = "null" ] && echo "" || echo "-d include_path=$PHPINCLUDEDIR:.")
UPDATERESULT=$(php $INCLUDEPATH $SCRIPTSDIR/update-scripted-spawns)
printf "  - $UPDATERESULT\n"

printf "* Cleaning up\n"
rm quarm-import.sql

printf "* Storing this version ($AVAILDATE) in $DBDUMPDIR/latest\n"
echo "$AVAILDATE" > $DBDUMPDIR/latest

printf "* Updating YAQDS version ($QUARMDBVER) in $VERSIONJSON\n"
echo "$( $JQBIN ".quarmDb = \"$QUARMDBVER\"" $VERSIONJSON)" > $VERSIONJSON

popd &> /dev/null